title: Beaker Browser
email: pfrazee@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://beakerbrowser.com" # the base hostname & protocol for your site
twitter_username: pfrazee
github_username:  pfrazee

# Build settings
markdown: kramdown
theme: minima
